---
- name: reload snmp exporter
  systemd:
    daemon_reload: true
    name: snmp_exporter
    state: reloaded

- name: restart snmp exporter
  systemd:
    daemon_reload: true
    name: snmp_exporter
    state: restarted
